# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('FH', 'Finish'), ('InP', 'In Progress')], default='FH', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project/%Y/%m/%d/')),
                ('members', models.ManyToManyField(to='skills.Members')),
            ],
        ),
    ]
